//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction_stages
    {
        public int stage_id { get; set; }
        public int object_id { get; set; }
        public string stage_name { get; set; }
        public System.DateTime stage_planned_start { get; set; }
        public System.DateTime stage_planned_end { get; set; }
        public Nullable<System.DateTime> stage_actual_start { get; set; }
        public Nullable<System.DateTime> stage_actual_end { get; set; }
        public string stage_status { get; set; }
    
        public virtual Construction_objects Construction_objects { get; set; }
    }
}
