//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction_objects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Construction_objects()
        {
            this.Construction_stages = new HashSet<Construction_stages>();
            this.Contracts = new HashSet<Contracts>();
            this.Object_materials = new HashSet<Object_materials>();
        }
    
        public int object_id { get; set; }
        public string object_name { get; set; }
        public string object_address { get; set; }
        public System.DateTime construction_start_date { get; set; }
        public Nullable<System.DateTime> construction_end_date { get; set; }
        public string construction_status { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Construction_stages> Construction_stages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Object_materials> Object_materials { get; set; }
    }
}
