//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int contract_id { get; set; }
        public int object_id { get; set; }
        public int contractor_id { get; set; }
        public System.DateTime contract_date { get; set; }
        public decimal contract_amount { get; set; }
        public string contract_number { get; set; }
    
        public virtual Construction_objects Construction_objects { get; set; }
        public virtual Contractors Contractors { get; set; }
    }
}
