//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstructionDB : DbContext
    {
        public ConstructionDB()
            : base("name=ConstructionDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Construction_objects> Construction_objects { get; set; }
        public virtual DbSet<Construction_stages> Construction_stages { get; set; }
        public virtual DbSet<Contractors> Contractors { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Object_materials> Object_materials { get; set; }
    }
}
