//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstructionApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object_materials
    {
        public int object_material_id { get; set; }
        public int object_id { get; set; }
        public int material_id { get; set; }
        public decimal material_quantity_used { get; set; }
        public System.DateTime material_delivery_date { get; set; }
    
        public virtual Construction_objects Construction_objects { get; set; }
        public virtual Materials Materials { get; set; }
    }
}
